# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: products.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'products.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eproducts.proto\x12\x08products\"$\n\x0eProductRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\" \n\x0fProductResponse\x12\r\n\x05price\x18\x01 \x01(\x05\x32X\n\x0eProductService\x12\x46\n\x0fGetProductPrice\x12\x18.products.ProductRequest\x1a\x19.products.ProductResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'products_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCTREQUEST']._serialized_start=28
  _globals['_PRODUCTREQUEST']._serialized_end=64
  _globals['_PRODUCTRESPONSE']._serialized_start=66
  _globals['_PRODUCTRESPONSE']._serialized_end=98
  _globals['_PRODUCTSERVICE']._serialized_start=100
  _globals['_PRODUCTSERVICE']._serialized_end=188
# @@protoc_insertion_point(module_scope)
