# Generated by Django 5.1 on 2024-08-23 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_user_id_orders_user_i'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='user_i',
            new_name='user_id',
        ),
    ]
